# Generated by Django 3.1.13 on 2022-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticketsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='serial_num',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Serial number'),
        ),
    ]
