# Generated by Django 3.1.13 on 2022-01-10 11:22

from django.db import migrations

from common.utils.timezone import as_current_tz


def fill_ticket_serial_number(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    tickets = Ticket.objects.all().order_by('date_created')

    today = '00000000'
    today_num = 1

    for ticket in tickets:
        # 跑这个脚本的时候，所有 ticket.serial_num == null
        date_created = as_current_tz(ticket.date_created)
        date_str = date_created.strftime('%Y%m%d')
        if date_str != today:
            today = date_str
            today_num = 1

        ticket.serial_num = today + '%04d' % today_num
        ticket.save()
        print(f'Fill ticket serial number: {ticket} -> {ticket.serial_num}')
        today_num += 1


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_serial_num'),
    ]

    operations = [
        migrations.RunPython(fill_ticket_serial_number)
    ]
